[package]
name = "ndarray_php"
version = "0.1.0"
edition = "2021"

[lib]
name = "ndarray_php"
crate-type = ["cdylib"]

[dependencies]
ndarray = { version = "0.17.2", features = ["serde", "std"] }
parking_lot = "0.12"
rand = "0.10.0"
rand_distr = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
cbindgen = "0.26"

[dev-dependencies]
# For testing
